steps:
- name:       node:16
  entrypoint: npm
  args:
  - install
- name:       node:16
  entrypoint: npm
  args:
  - run
  - deploy:${_NODE_ENV}
  env:
  - 'FIREBASE_TOKEN=${_FIREBASE_TOKEN}'
  - 'ACCESS_TOKEN=${_ACCESS_TOKEN}'
