steps:
  - name: node:20
    entrypoint: npm
    args:
      - install
  - name: node:20
    entrypoint: npm
    args:
      - run
      - deploy:${_NODE_ENV}
    env:
      - "ACCESS_TOKEN=${_ACCESS_TOKEN}"
      - "NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}"
