import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Flex, Box } from "@chakra-ui/layout";
import { useMediaQuery } from "@chakra-ui/media-query";
import { useTheme } from "@chakra-ui/system";
import Prismic from "@prismicio/client";
import SideBar from "../src/flat/SideBar";
import Hero from "../src/flat/Hero";
import Separator from "../src/flat/Separator";
import Trends from "../src/flat/Trends";
import Insights from "../src/flat/Insights";
import Tasks from "../src/flat/Tasks";
import OurPanel from "../src/flat/OurPanel";
import Footer from "../src/flat/Footer";
import Header from "../src/flat/Header";
import { Client } from "../prismicHelpers";
import { extractBlogDataFromPrisma } from "../prismicHelpers";
import styles from "../styles/Home.module.css";

interface HomeProps {
  docs: any;
}

const Home = ({ docs }: HomeProps) => {
  const { breakpoints } = useTheme();
  const [isSmallerThan768] = useMediaQuery(`(max-width: ${breakpoints.md})`);
  console.log("docs", docs);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex w="100%" h="100%">
        {!isSmallerThan768 && <SideBar />}
        <Flex flexFlow="column" className={styles.homePage}>
          <Hero />
          <Separator title="Our blog" />
          <Trends data={docs} />
          <Separator title="Solutions" src="/thing2.svg" />
          <Insights data={docs} />
          <Tasks data={docs} />
          <Separator title="Our panel" />
          <OurPanel />
          <Footer />
        </Flex>
      </Flex>
    </>
  );
};

export async function getStaticProps() {
  const docs = await Client().query(
    Prismic.Predicates.at("document.type", "blog")
  );

  return {
    props: {
      docs: extractBlogDataFromPrisma(docs),
    },
  };
}

export default Home;
