import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Flex, Box } from "@chakra-ui/layout";
import { useMediaQuery } from "@chakra-ui/media-query";
import { useTheme } from "@chakra-ui/system";
import Prismic from "@prismicio/client";
import SideBar from "../src/flat/SideBar";
import Hero from "../src/flat/Hero";
import Separator from "../src/flat/Separator";
import Trends from "../src/flat/Trends";
import Insights from "../src/flat/Insights";
import Tasks from "../src/flat/Tasks";
import OurPanel from "../src/flat/OurPanel";
import Footer from "../src/flat/Footer";
import { Client } from "../prismicHelpers";
import styles from "../styles/Home.module.css";

interface HomeProps {
  docs: any;
  blog_posts: any;
}

const Home = ({ docs, blog_posts }: HomeProps) => {
  const { breakpoints } = useTheme();
  const [isSmallerThan768] = useMediaQuery(`(max-width: ${breakpoints.md})`);

  console.log("sliced_blog_posts", docs);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex w="100%" h="100%">
        {!isSmallerThan768 && <SideBar />}
        <Flex flexFlow="column" className={styles.homePage}>
          <Hero />
          <Separator title="Our blog" />
          <Trends data={docs} />
          <Separator title="Solutions" />
          <Insights />
          <Tasks />
          <Separator title="Our panel" />
          <OurPanel />
          <Footer />
        </Flex>
      </Flex>
    </>
  );
};

export async function getStaticProps() {
  const sliced_blog_posts = await Client().query(
    Prismic.Predicates.at("document.type", "blog-post")
  );

  const blog_posts = await Client().query(
    Prismic.Predicates.at("document.type", "bl")
  );

  return {
    props: {
      docs: sliced_blog_posts.results,
      blog_posts: blog_posts.results,
    },
  };
}

export default Home;
