import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Flex, Box } from "@chakra-ui/layout";
import { useMediaQuery } from "@chakra-ui/media-query";
import { useTheme } from "@chakra-ui/system";
import SideBar from "../src/flat/SideBar";
import Hero from "../src/flat/Hero";
import Separator from "../src/flat/Separator";
import Trends from "../src/flat/Trends";
import Header from "../src/flat/Header";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const {breakpoints} = useTheme();
  const [isSmallerThan768] = useMediaQuery(`(max-width: ${breakpoints.md})`);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex w="100%" h="100%">
        {!isSmallerThan768 && <SideBar />}
        <Flex flexFlow="column" className={styles.homePage}>
          <Hero />
          <Separator title="Our blog" />
          <Trends />
          <Separator title="Solutions" src="/thing2.svg"/>
        </Flex>
      </Flex>
    </>
  );
};

export default Home;
